apiVersion: v1
kind: Service
metadata:
  name: demohello
spec:
  type: NodePort
  selector:
    app: demohello
  ports:
    - protocol: TCP
      nodePort: 30100
      port: 80
      targetPort: http
