apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: jwang1568cicd
spec:
  storageClassName: jenkins-pv
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/jenkins-volume/
